tasks:
    - init: CC=clang-11 make -B && exec ./basque
image:
    file: .gitpod.Dockerfile
ports:
    - port: 5900
      onOpen: ignore
    - port: 6080
      onOpen: open-browser
    - port: 35900
      onOpen: ignore

vscode:
    extensions:
        - xaver.clang-format@1.9.0:auCYfQ5pnsZ6Cjf4ZxkAtA==
